release:
  <service-name>: <tag>

commons:
  imageRepo: <repo-server>/path/to/repo
  
  clusterType: <cluster-type> # ocp / k8s / k8s, currently affects expose options, and will add default security options for openshift clusters

  pullSecret:
    dockerconfigjson: <b64encoded-auth>

  resources:
    limits:
      cpu: 10m
      memory: 100Mi
    requests:
      cpu: 10m
      memory: 100Mi

  rbac:
    - name: <role-name>
      rules:
        - apiGroups:
            - ""
          verbs:
            - <verb> # get, list, watch, etc
          resources:
            - <resource> # deployments, secrets, etc
      bindTo:
        - <service-name>

  # These can be nounted to any service when specified in the filesFrom field
  globalFiles:
    <grouped-files-name>:
      dir: dir # globalFiles can include an entire directory together
    <globalFile-name>:
      file: <file-path> # globalFiles can also include a single file, they can also do both when both keys are specified
  # These can be nounted to any service when specified in the filesFrom field
  globalEnv:
    <config-name>:
      content: # as key value pairs
        <key>: <value>
        <key2>: <value>
      secret: <is-secret> # True or False

  pvcs:
    - name: <volume-claim-name>
      size: "" # in Gi
      accessMode: <accessMode> # Read(Only/Write)(Once/Many) depends on storageClass requirements
      pvBind: <pv-name> # In case a static persistant volume is needed, one can be configured here
      storageClass: "" # Optional

services:
  generic: # Every config in this section except name is optional
    - name: <service-name>

      # image: <override-image> # Default uses one specified in release section

      ports: # Use if application listens on any port
        - name: <port-name>
          protocol: <protocol> # Usually TCP or UDP
          port: <listening-port-in-app>
          expsoe: # in case the app is exposed outside the cluster, will create ingresses or routes depending on the cluster type
            url: <desired-application-host> # With http url paths (Such as /foo/bar) Please check that the DNS record exists
            subdomain: <desired-subdomain> # subdomain only, the route will be created under the cluster domain, when using openshift
            ingressClass: <class-type> # Optional as usually clusters have a default configured
            externalCert: <key-cert-secret-ref> # When the route needs to handle https connections by itself

      ### ENVS AND FILES
      # this mounts only to this service
      env:
        <key>: <value>
        <other-key>: <other-value>
      # these will mount only to this service
      files:
        - dir: dir
          mountPath: <path-in-container>
          # file: <file-path> # This can also be used instead or with dir

      # Use this to mount a global config as environment variables
      envFrom:
        - <globalConfig-name>
      # Use this to mount a globalFile as files in the pod
      filesFrom:
        - name: <globalFile-name>
          mountPath: <path-in-container>

      # Use this to mount pvc s to the pod
      pvc:
        - name: <pvc-name>
          mountPath: <path-in-pod>

      replicaCount: 1 # Optional
      entrypoint: <command-to-execute> # As you would write it in terminal

      # Use this to override default resources defined in the commons section
      resources:
        limits:
          cpu: 150m
          memory: 0.25Gi
        requests:
          cpu: 70m
          memory: 0.25Gi
  jobs: # Every config in this section except name is optional
    - name: <job-name>

      # image: <override-image> # Default uses one specified in release section
      # cron: <time> # By cron Rules if empty/ null it would be a regular job

      ### ENVS AND FILES
      # this mounts only to this job
      env:
        <key>: <value>
        <other-key>: <other-value>
      # these will mount only to this job
      files:
        - dir: <directory-path>
          mountPath: <path-in-container>
          # file: <file-path> # This can also be used instead or with dir

      # Use this to mount a global config as environment variables
      envFrom:
        - <globalConfig-name>
      # Use this to mount a globalFile as files in the pod
      filesFrom:
        - name: <globalFile-name>
          mountPath: <path-in-container>

      # Use this to mount pvc s to the pod
      pvc:
        - name: <pvc-name>
          mountPath: <path-in-pod>

      replicaCount: 1 # Optional
      entrypoint: <command-to-execute> # As you would write it in terminal

      # Use this to override default resources defined in the commons section
      resources:
        limits:
          cpu: 150m
          memory: 0.25Gi
        requests:
          cpu: 70m
          memory: 0.25Gi
