{{- define "mesopotamia.global.pull-secret" }}
{{- with .Values.commons.pullSecret }}
kind: Secret
apiVersion: v1
metadata:
  name: pull-secret
data:
  .dockerconfigjson: {{ .dockerconfigjson }}
type: kubernetes.io/dockerconfigjson
---
{{- end }}
{{- end }}